name: Deploy to Server

on:
  push:
    branches:
      - main # ganti ke branch kamu kalau beda

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Test koneksi SSH dulu
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ""
          script: whoami
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_B64 }}

      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Build binary
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o dev-kasir .

      - name: Copy binary ke server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dev-kasir"
          target: "/home/dev-kasir.kavi.co.id/backend"

      - name: Restart service di server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart dev-kasir-kavi
            sudo systemctl status dev-kasir-kavi --no-pager
